return {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  filestatus = {
    Modified = "",
    Readonly = " ",
    Unnamed = " ",
  },
  which_key = {
    command = " ",
    explorer = "󰥨 ",
    file = "󰈞 ",
    flash = " ",
    fuzzy = " ",
    help = "󰋖 ",
    latex = " ",
    mark = "󰍎 ",
    note = " ",
    splitH = "󰤻 ",
    splitV = "󰤼 ",
    swap = " ",
    tree = " ",
    undo = " ",
  },
  mode = {
    ["NORMAL"] = ' ',
    ['O-PENDING'] = ' ',
    ["INSERT"] = ' ',
    ["VISUAL"] = ' ',
    ["V-LINE"] = ' ',
    ['V-BLOCK'] = ' 󰕭',
    ["COMMAND"] = ' ',
    ["REPLACE"] = ' ',
    ['TERMINAL'] = ' ',
    ['EX'] = 'X',
    ['SELECT'] = '󰒉 ',
    ['S-LINE'] = '󰒉 ',
    ['S-BLOCK'] = '󰒉 󰕭',
  },
  mason = {
    installed = "✓",
    pending = "➜",
    uninstalled = "✗",
  },
}
